name: Nuclie Reconnaissance

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL to perform reconnaissance on'
        required: true

jobs:
  reconnaissance:
    name: Nuclie Reconnaissance
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nuclie
      run: |
        wget https://github.com/projectdiscovery/nuclei/releases/download/v2.7.4/nuclei_2.7.4_linux_amd64.tar.gz
        tar xvzf nuclei_2.7.4_linux_amd64.tar.gz
        sudo mv nuclei /usr/local/bin/

    - name: Perform reconnaissance
      run: nuclei -u ${{ github.event.inputs.target_url }} -t ~/nuclei-templates

    - name: Display output
      run: cat ~/nuclei-templates/results/*.txt
