name: Nuclie Reconnaissance

on:
  workflow_dispatch:

jobs:
  reconnaissance:
    name: Nuclie Reconnaissance
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nuclie
      timeout-minutes: 2
      run: |
        git clone https://github.com/Escartem/InfiniteCraftSearch
        cd InfiniteCraftSearch
        pip3 install requests
        python3 infinite_craft.py

    - name: Display output
      run: cat craft_result.json
